name: API Tests Newman

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Rodar testes
        run: npm run report

      - name: Salvar relatório HTML
        uses: actions/upload-artifact@v6
        with:
          name: newman-report
          path: newman-report.html